let gags = {
    "toon-up": {
        1: {
            "name": "Feather",
            "minimum-dmg": 8,
            "maximum-dmg": 10,
            "base-acc": 70,
        },
        2: {
            "name": "Megaphone",
            "minimum-dmg": 15,
            "maximum-dmg": 18,
            "base-acc": 70,
        },
        3: {
            "name": "Lipstick",
            "minimum-dmg": 27,
            "maximum-dmg": 30,
            "base-acc": 70,
        },
        4: {
            "name": "Bamboo Cane",
            "minimum-dmg": 40,
            "maximum-dmg": 45,
            "base-acc": 70,
        },
        5: {
            "name": "Pixie Dust",
            "minimum-dmg": 50,
            "maximum-dmg": 60,
            "base-acc": 70,
        },
        6: {
            "name": "Juggling Cubes",
            "minimum-dmg": 75,
            "maximum-dmg": 105,
            "base-acc": 70,
        },
        7: {
            "name": "High Dive",
            "minimum-dmg": 210,
            "maximum-dmg": 210,
            "base-acc": 95,
        },
    },
    "trap": {
        1: {
            "name": "Banana Peel",
            "minimum-dmg": 10,
            "maximum-dmg": 12,
            "base-acc": 0,
        },
        2: {
            "name": "Rake",
            "minimum-dmg": 18,
            "maximum-dmg": 20,
            "base-acc": 0,
        },
        3: {
            "name": "Marbles",
            "minimum-dmg": 30,
            "maximum-dmg": 35,
            "base-acc": 0,
        },
        4: {
            "name": "Quicksand",
            "minimum-dmg": 45,
            "maximum-dmg": 50,
            "base-acc": 0,
        },
        5: {
            "name": "Trapdoor",
            "minimum-dmg": 75,
            "maximum-dmg": 85,
            "base-acc": 0,
        },
        6: {
            "name": "TNT",
            "minimum-dmg": 90,
            "maximum-dmg": 180,
            "base-acc": 0,
        },
        7: {
            "name": "Railroad",
            "minimum-dmg": 200,
            "maximum-dmg": 200,
            "base-acc": 0,
        },
    },
    "lure": {
        1: {
            "name": "$1 Bill",
            "minimum-dmg": 0,
            "maximum-dmg": 0,
            "base-acc": 60,
        },
        2: {
            "name": "Small Magnet",
            "minimum-dmg": 0,
            "maximum-dmg": 0,
            "base-acc": 55,
        },
        3: {
            "name": "$5 Bill",
            "minimum-dmg": 0,
            "maximum-dmg": 0,
            "base-acc": 70,
        },
        4: {
            "name": "Big Magnet",
            "minimum-dmg": 0,
            "maximum-dmg": 0,
            "base-acc": 65,
        },
        5: {
            "name": "$10 Bill",
            "minimum-dmg": 0,
            "maximum-dmg": 0,
            "base-acc": 80,
        },
        6: {
            "name": "Hypno Goggles",
            "minimum-dmg": 0,
            "maximum-dmg": 0,
            "base-acc": 75,
        },
        7: {
            "name": "Presentation",
            "minimum-dmg": 0,
            "maximum-dmg": 0,
            "base-acc": 90,
        },
    },
    "sound": {
        1: {
            "name": "Bike Horn",
            "minimum-dmg": 3,
            "maximum-dmg": 4,
            "base-acc": 95,
        },
        2: {
            "name": "Whistle",
            "minimum-dmg": 5,
            "maximum-dmg": 7,
            "base-acc": 95,
        },
        3: {
            "name": "Bugle",
            "minimum-dmg": 9,
            "maximum-dmg": 11,
            "base-acc": 95,
        },
        4: {
            "name": "Aoogah",
            "minimum-dmg": 14,
            "maximum-dmg": 16,
            "base-acc": 95,
        },
        5: {
            "name": "Elephant Trunk",
            "minimum-dmg": 19,
            "maximum-dmg": 21,
            "base-acc": 95,
        },
        6: {
            "name": "Foghorn",
            "minimum-dmg": 25,
            "maximum-dmg": 50,
            "base-acc": 95,
        },
        7: {
            "name": "Opera Singer",
            "minimum-dmg": 90,
            "maximum-dmg": 90,
            "base-acc": 95,
        },
    },
    "throw": {
        1: {
            "name": "Cupcake",
            "minimum-dmg": 4,
            "maximum-dmg": 6,
            "base-acc": 75,
        },
        2: {
            "name": "Fruit Pie Slice",
            "minimum-dmg": 8,
            "maximum-dmg": 10,
            "base-acc": 75,
        },
        3: {
            "name": "Cream Pie Slice",
            "minimum-dmg": 14,
            "maximum-dmg": 17,
            "base-acc": 75,
        },
        4: {
            "name": "Whole Fruit Pie",
            "minimum-dmg": 24,
            "maximum-dmg": 27,
            "base-acc": 75,
        },
        5: {
            "name": "Whole Cream Pie",
            "minimum-dmg": 36,
            "maximum-dmg": 40,
            "base-acc": 75,
        },
        6: {
            "name": "Birthday Cake",
            "minimum-dmg": 48,
            "maximum-dmg": 100,
            "base-acc": 75,
        },
        7: {
            "name": "Wedding Cake",
            "minimum-dmg": 120,
            "maximum-dmg": 120,
            "base-acc": 75,
        },
    },
    "squirt": {
        1: {
            "name": "Squirting Flower",
            "minimum-dmg": 3,
            "maximum-dmg": 4,
            "base-acc": 95,
        },
        2: {
            "name": "Glass of Water",
            "minimum-dmg": 6,
            "maximum-dmg": 8,
            "base-acc": 95,
        },
        3: {
            "name": "Squirt Gun",
            "minimum-dmg": 10,
            "maximum-dmg": 12,
            "base-acc": 95,
        },
        4: {
            "name": "Seltzer Bottle",
            "minimum-dmg": 18,
            "maximum-dmg": 21,
            "base-acc": 95,
        },
        5: {
            "name": "Fire Hose",
            "minimum-dmg": 27,
            "maximum-dmg": 30,
            "base-acc": 95,
        },
        6: {
            "name": "Storm Cloud",
            "minimum-dmg": 36,
            "maximum-dmg": 80,
            "base-acc": 95,
        },
        7: {
            "name": "Geyser",
            "minimum-dmg": 105,
            "maximum-dmg": 105,
            "base-acc": 95,
        },
    },
    "drop": {
        1: {
            "name": "Flower Pot",
            "minimum-dmg": 10,
            "maximum-dmg": 10,
            "base-acc": 50,
        },
        2: {
            "name": "Sandbag",
            "minimum-dmg": 18,
            "maximum-dmg": 18,
            "base-acc": 50,
        },
        3: {
            "name": "Anvil",
            "minimum-dmg": 30,
            "maximum-dmg": 30,
            "base-acc": 50,
        },
        4: {
            "name": "Big Weight",
            "minimum-dmg": 45,
            "maximum-dmg": 45,
            "base-acc": 50,
        },
        5: {
            "name": "Safe",
            "minimum-dmg": 60,
            "maximum-dmg": 70,
            "base-acc": 50,
        },
        6: {
            "name": "Grand Piano",
            "minimum-dmg": 85,
            "maximum-dmg": 170,
            "base-acc": 50,
        },
        7: {
            "name": "Toontanic",
            "minimum-dmg": 180,
            "maximum-dmg": 180,
            "base-acc": 50,
        },
    },
};